version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: ./app.Dockerfile
    container_name: taskmgmt_app
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
    command: >
      sh -c "npx prisma migrate deploy &&
             npm start"
    networks:
      app-net: {}

networks:
  app-net:
    external: true
    name: "video-platform-net"